Fixes and enhancements
* Fix AttributeError: 'dict' object has no attribute 'set'

  This error causes migrating old settings to fail.

* Skip migrating settings that are the same as the default values.

  This results in less noise in the user settings file.